CREATE TABLE User (
	ID SMALLINT AUTO_INCREMENT NOT NULL UNIQUE,
	Username VARCHAR(10) NOT NULL UNIQUE,
	FirstName VARCHAR(20) NOT NULL,
	LastName VARCHAR(20) NOT NULL,
	Password VARCHAR(20) NOT NULL,
	PRIMARY KEY (ID, Username)
) DEFAULT CHARACTER SET utf8 ENGINE=InnoDB;

CREATE TABLE Tank (
	ID SMALLINT AUTO_INCREMENT NOT NULL,
	UserID SMALLINT,
	CurrTemp REAL NOT NULL,
	TargetTemp REAL NOT NULL,
	WaterFlow BOOLEAN NOT NULL,
	Lights BOOLEAN NOT NULL,
	LightColour VARCHAR(10) NOT NULL CHECK (LightColour IN ('red', 'green', 'blue', 'white', 'yellow', 'purple', 'multi')),
	Name VARCHAR(20),
	Model VARCHAR(20),
	PRIMARY KEY(ID),
	FOREIGN KEY (UserID) REFERENCES User(ID)
) DEFAULT CHARACTER SET utf8 ENGINE=InnoDB;

CREATE TABLE Fish (
	ID SMALLINT AUTO_INCREMENT NOT NULL UNIQUE,
	Name VARCHAR(20) NOT NULL,
	Picture VARCHAR(30) NOT NULL,
	TempLow REAL,
	TempHigh REAL,
	Compatible VARCHAR(255),
	Description VARCHAR(120),
	Type INT,
	PRIMARY KEY (ID, Name)
) DEFAULT CHARACTER SET utf8 ENGINE=InnoDB;

CREATE TABLE InTank (
	TankID SMALLINT NOT NULL,
	FishID SMALLINT NOT NULL,
	PRIMARY KEY (TankID, FishID),
	FOREIGN KEY (TankID) REFERENCES Tank(ID),
	FOREIGN KEY (FishID) REFERENCES Fish(ID)
) DEFAULT CHARACTER SET utf8 ENGINE=InnoDB;